name: recipe_scraper
description: A Dart package that allows you to scrape recipe data from websites using JSON-LD structured data (schema.org Recipe markup).
version: 1.0.0
repository: https://github.com/Malte2036/recipe_scraper
topics:
  - recipe
  - scraper
  - json-ld
  - schema

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  html: ^0.15.4
  http: ^1.5.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
