name: recipe_scraper
description: A package to scrape recipes from various websites.
version: 0.0.1
repository: https://github.com/Malte2036/recipe_scraper

environment:
  sdk: ^3.1.3

dependencies:
  html: ^0.15.4
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
